# Generated by Django 5.0.7 on 2024-11-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saintke', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('predicted_price', models.FloatField()),
                ('actual_price', models.FloatField(blank=True, null=True)),
                ('action_taken', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('HOLD', 'Hold')], max_length=10)),
                ('reward', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
