# Generated by Django 5.0.7 on 2025-03-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saintke', '0004_planrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planrequest',
            name='reason',
            field=models.CharField(choices=[('basic', 'Basic Plan'), ('premium', 'Premium Plan'), ('vip', 'VIP Plan')], max_length=20),
        ),
    ]
